services:
  order-ms:
    image: postgres:17.9
    container_name: order
    hostname: order
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order
    networks:
        - saga-micro-service
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/5432" ]
      interval: 10s
      retries: 5


  payment-ms:
    image: postgres:17.9
    container_name: payment
    hostname: payment
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment
    networks:
       - saga-micro-service
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/5432" ]
      interval: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.14
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      order-ms:
        condition: service_healthy
      payment-ms:
        condition: service_healthy
    networks:
      - saga-micro-service

  broker:
    image: apache/kafka:latest
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: unless-stopped
    networks:
      - saga-micro-service
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 10s
      retries: 5


  kafka-front-end:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-front-end
    hostname: kafka-front-end
    depends_on:
      - broker
    restart: unless-stopped
    ports:
      - "8082:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
    networks:
      - saga-micro-service


networks:
  saga-micro-service:
    name: saga-micro-service
    driver: bridge


